# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.5.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QMainWindow, QMenu, QMenuBar,
    QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 541)
        MainWindow.setStyleSheet(u"")
        self.actionUsuarios_cadastrados = QAction(MainWindow)
        self.actionUsuarios_cadastrados.setObjectName(u"actionUsuarios_cadastrados")
        self.actionEditar_usuario = QAction(MainWindow)
        self.actionEditar_usuario.setObjectName(u"actionEditar_usuario")
        self.actionSair = QAction(MainWindow)
        self.actionSair.setObjectName(u"actionSair")
        self.actionCadastro_de_produtos = QAction(MainWindow)
        self.actionCadastro_de_produtos.setObjectName(u"actionCadastro_de_produtos")
        self.actionEditar_produtos = QAction(MainWindow)
        self.actionEditar_produtos.setObjectName(u"actionEditar_produtos")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionVendas_por_Usuario = QAction(MainWindow)
        self.actionVendas_por_Usuario.setObjectName(u"actionVendas_por_Usuario")
        self.actionPor_tipo = QAction(MainWindow)
        self.actionPor_tipo.setObjectName(u"actionPor_tipo")
        self.actionPor_codigo = QAction(MainWindow)
        self.actionPor_codigo.setObjectName(u"actionPor_codigo")
        self.actionTotal = QAction(MainWindow)
        self.actionTotal.setObjectName(u"actionTotal")
        self.actionPor_usuario = QAction(MainWindow)
        self.actionPor_usuario.setObjectName(u"actionPor_usuario")
        self.actionVenda_no_terminal = QAction(MainWindow)
        self.actionVenda_no_terminal.setObjectName(u"actionVenda_no_terminal")
        self.actionNovo_Ticket = QAction(MainWindow)
        self.actionNovo_Ticket.setObjectName(u"actionNovo_Ticket")
        self.actionGerenciar_Ticket = QAction(MainWindow)
        self.actionGerenciar_Ticket.setObjectName(u"actionGerenciar_Ticket")
        self.actionExcluir_Ticket = QAction(MainWindow)
        self.actionExcluir_Ticket.setObjectName(u"actionExcluir_Ticket")
        self.actionConsultar_Ticket = QAction(MainWindow)
        self.actionConsultar_Ticket.setObjectName(u"actionConsultar_Ticket")
        self.actionCadastrar_Usuario = QAction(MainWindow)
        self.actionCadastrar_Usuario.setObjectName(u"actionCadastrar_Usuario")
        self.actionNovo_Cliente = QAction(MainWindow)
        self.actionNovo_Cliente.setObjectName(u"actionNovo_Cliente")
        self.actionEditar_Cliente = QAction(MainWindow)
        self.actionEditar_Cliente.setObjectName(u"actionEditar_Cliente")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 21))
        self.menuCadastro = QMenu(self.menubar)
        self.menuCadastro.setObjectName(u"menuCadastro")
        self.menuUsuario = QMenu(self.menuCadastro)
        self.menuUsuario.setObjectName(u"menuUsuario")
        self.menuProdutos = QMenu(self.menuCadastro)
        self.menuProdutos.setObjectName(u"menuProdutos")
        self.menuTickets = QMenu(self.menuCadastro)
        self.menuTickets.setObjectName(u"menuTickets")
        self.menuCliente = QMenu(self.menuCadastro)
        self.menuCliente.setObjectName(u"menuCliente")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuRelatorios = QMenu(self.menubar)
        self.menuRelatorios.setObjectName(u"menuRelatorios")
        self.menuProdutos_2 = QMenu(self.menuRelatorios)
        self.menuProdutos_2.setObjectName(u"menuProdutos_2")
        self.menuVendas_2 = QMenu(self.menuRelatorios)
        self.menuVendas_2.setObjectName(u"menuVendas_2")
        self.menuVendas = QMenu(self.menubar)
        self.menuVendas.setObjectName(u"menuVendas")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuCadastro.menuAction())
        self.menubar.addAction(self.menuVendas.menuAction())
        self.menubar.addAction(self.menuRelatorios.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuCadastro.addAction(self.menuUsuario.menuAction())
        self.menuCadastro.addAction(self.menuProdutos.menuAction())
        self.menuCadastro.addAction(self.menuTickets.menuAction())
        self.menuCadastro.addAction(self.menuCliente.menuAction())
        self.menuCadastro.addSeparator()
        self.menuCadastro.addAction(self.actionSair)
        self.menuUsuario.addAction(self.actionCadastrar_Usuario)
        self.menuUsuario.addAction(self.actionUsuarios_cadastrados)
        self.menuUsuario.addAction(self.actionEditar_usuario)
        self.menuProdutos.addAction(self.actionCadastro_de_produtos)
        self.menuProdutos.addAction(self.actionEditar_produtos)
        self.menuTickets.addAction(self.actionNovo_Ticket)
        self.menuTickets.addAction(self.actionGerenciar_Ticket)
        self.menuTickets.addAction(self.actionExcluir_Ticket)
        self.menuTickets.addSeparator()
        self.menuTickets.addAction(self.actionConsultar_Ticket)
        self.menuCliente.addAction(self.actionNovo_Cliente)
        self.menuCliente.addAction(self.actionEditar_Cliente)
        self.menuAbout.addAction(self.actionAbout)
        self.menuRelatorios.addAction(self.menuProdutos_2.menuAction())
        self.menuRelatorios.addAction(self.menuVendas_2.menuAction())
        self.menuProdutos_2.addAction(self.actionPor_tipo)
        self.menuProdutos_2.addAction(self.actionPor_codigo)
        self.menuVendas_2.addAction(self.actionTotal)
        self.menuVendas_2.addAction(self.actionPor_usuario)
        self.menuVendas.addAction(self.actionVenda_no_terminal)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Sistema de gerenciamento de vendas", None))
        self.actionUsuarios_cadastrados.setText(QCoreApplication.translate("MainWindow", u"Usuarios cadastrados", None))
        self.actionEditar_usuario.setText(QCoreApplication.translate("MainWindow", u"Editar usuario", None))
        self.actionSair.setText(QCoreApplication.translate("MainWindow", u"Sair", None))
        self.actionCadastro_de_produtos.setText(QCoreApplication.translate("MainWindow", u"Cadastro de produtos", None))
        self.actionEditar_produtos.setText(QCoreApplication.translate("MainWindow", u"Editar produtos", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionVendas_por_Usuario.setText(QCoreApplication.translate("MainWindow", u"Vendas por Usuario", None))
        self.actionPor_tipo.setText(QCoreApplication.translate("MainWindow", u"Por tipo", None))
        self.actionPor_codigo.setText(QCoreApplication.translate("MainWindow", u"Por codigo", None))
        self.actionTotal.setText(QCoreApplication.translate("MainWindow", u"Total", None))
        self.actionPor_usuario.setText(QCoreApplication.translate("MainWindow", u"Por usuario", None))
        self.actionVenda_no_terminal.setText(QCoreApplication.translate("MainWindow", u"Venda no terminal", None))
        self.actionNovo_Ticket.setText(QCoreApplication.translate("MainWindow", u"Novo Ticket", None))
        self.actionGerenciar_Ticket.setText(QCoreApplication.translate("MainWindow", u"Gerenciar Ticket", None))
        self.actionExcluir_Ticket.setText(QCoreApplication.translate("MainWindow", u"Excluir Ticket", None))
        self.actionConsultar_Ticket.setText(QCoreApplication.translate("MainWindow", u"Consultar Ticket", None))
        self.actionCadastrar_Usuario.setText(QCoreApplication.translate("MainWindow", u"Cadastrar Usuario", None))
        self.actionNovo_Cliente.setText(QCoreApplication.translate("MainWindow", u"Novo Cliente", None))
        self.actionEditar_Cliente.setText(QCoreApplication.translate("MainWindow", u"Editar Cliente", None))
        self.menuCadastro.setTitle(QCoreApplication.translate("MainWindow", u"Cadastro", None))
        self.menuUsuario.setTitle(QCoreApplication.translate("MainWindow", u"Usuario", None))
        self.menuProdutos.setTitle(QCoreApplication.translate("MainWindow", u"Produtos", None))
        self.menuTickets.setTitle(QCoreApplication.translate("MainWindow", u"Tickets", None))
        self.menuCliente.setTitle(QCoreApplication.translate("MainWindow", u"Cliente", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"About", None))
        self.menuRelatorios.setTitle(QCoreApplication.translate("MainWindow", u"Relatorios", None))
        self.menuProdutos_2.setTitle(QCoreApplication.translate("MainWindow", u"Produtos", None))
        self.menuVendas_2.setTitle(QCoreApplication.translate("MainWindow", u"Vendas", None))
        self.menuVendas.setTitle(QCoreApplication.translate("MainWindow", u"Vendas", None))
    # retranslateUi

